name: docker-python3-opencv

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 5 * * 1'  # Every monday at 5:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  image:
    name: python3-opencv:${{ matrix.arch_name }}-${{ matrix.type.preffix }}${{ matrix.version }}${{ matrix.type.suffix }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: ["4.5.2", "4.4.0", "4.3.0", "4.2.0", "4.1.2", "4.0.1", "3.4.14"]
        arch_name: [amd64, arm64, arm, ppc64le, s390x]
        type: 
        - { name: "opencv", folder: "opencv", preffix: "", suffix: ""}
        - { name: "opencv_contrib", folder: "opencv_contrib", preffix: "", suffix: "-contrib"}
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.2.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "Docker QEMU"
        run: make qemu_x86
      - name: "🛠️ Build"
        run: docker buildx build -t bensuperpc/python3-opencv:${{ matrix.arch_name }}-${{ matrix.type.preffix }}${{ matrix.version }}${{ matrix.type.suffix }} -t bensuperpc/python3-opencv:${{ matrix.arch_name }}-${{ matrix.type.preffix }}${{ matrix.version }}${{ matrix.type.suffix }}-$(date '+%Y%m%d')-$(git rev-parse --short HEAD) -f ${{ matrix.type.folder }}/Dockerfile  . --build-arg OPENCV_VERSION=${{ matrix.version }} --build-arg DOCKER_IMAGE=python:3.9 --build-arg BUILD_DATE=$(date +%Y-%m-%d_%H:%M:%S) --platform linux/${{ matrix.arch_name }}
      - name: "📤 Upload to hub.docker.com"
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            docker image push bensuperpc/python3-opencv --all-tags
